name: Build Android APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Descargar c√≥digo
      uses: actions/checkout@v2
    
    - name: Instalar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Instalar Buildozer
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk python3-pip
        pip3 install buildozer cython==0.29.28
    
    - name: Construir APK
      run: |
        buildozer -v android debug
    
    - name: Subir APK
      uses: actions/upload-artifact@v2
      with:
        name: mi-app-android
        path: bin/*.apk
